print("Welcome to the band name generator")
city_name = input("what's name of the city you grew up in?\n")
pet_name = input("what's your pet's name?\n")
print("your band name could be "+ city_name + " " + pet_name)
print("your band name could be {} {}".format(city_name,pet_name))